name: Back PR Merged

on:
  pull_request:
    types: [closed]
    branches: [dev]
    paths:
    - 'force-app/**'

jobs:
  deploy-scratch-dev:
    if: github.event.pull_request.base.ref == 'dev' && github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[BACK PR]')
    uses: ./.github/workflows/deploy.yml
    secrets:
      SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_SCRATCH_EX }}

  deploy-scratch-stage:
    if: github.event.pull_request.base.ref == 'stage' && github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[BACK PR]')
    uses: ./.github/workflows/deploy.yml
    secrets:
      SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
