name: Back Propagate

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  back-propagate:
    environment: ${{ inputs.env_name }}
    runs-on: ubuntu-latest
    steps:
      - name: "Create PR"
        run: gh pr create -B ${{ inputs.env_name }} -H main --title '${{ github.event.pull_request.title }}' --body 'Created by GitHub Action'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}