name: Back Propagate - PR

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

jobs:
  back-propagate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Set up git config"
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions@github.com"

      - name: "Create PR"
        run: |
          NEW_BRANCH_NAME=$(echo "gh_actions/${{ github.event.pull_request.head.ref }}__${{ inputs.branch_name }}" | sed 's/ /_/g')
          git fetch --all
          git checkout ${{ inputs.branch_name }}
          git checkout -b $NEW_BRANCH_NAME
          git merge main --no-edit
          git push -f -u origin $NEW_BRANCH_NAME
          gh pr create -B ${{ inputs.branch_name }} -H $NEW_BRANCH_NAME --title '[BACK PR] ${{ github.event.pull_request.title }}' --body '${{ github.event.pull_request.body }}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
