name: Back Propagate - PR

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

jobs:
  back-propagate:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Create PR"
        run: gh pr create -B ${{ inputs.branch_name }} -H main --title '[BACK PR] ${{ github.event.pull_request.title }}' --body 'Created by GitHub Action\n\n ${{ github.event.pull_request.body }}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
