name: Back Propagate

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  back-propagate:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Create PR"
        if: github.event.pull_request.merged == true
        run: gh pr create -B main -H test-destination --title '${{ github.event.pull_request.title }}' --body 'Created by GitHub Action'
        env:
          name: dev
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
