name: Back PR Merged

on:
  pull_request:
    types: [closed]
    branches: [dev]
    paths:
    - 'force-app/**'

jobs:
  deploy-scratch-dev:
    if: github.event.pull_request.base.ref == 'dev' && github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[BACK PR]')
    uses: ./.github/workflows/deploy.yml
    secrets:
      sfdx_token: ${{ secrets.SFDX_AUTH_URL }}

  close-stale-prs:
    runs-on: ubuntu-latest
    needs: [deploy-scratch-dev]
    steps:
      - name: Close stale PRs
        run: |
          CREATED=${{ github.event.pull_request.created_at }}
          BRANCH=${{ github.event.pull_request.base.ref }}
          echo $CREATED
          echo $BRANCH
          for pr_number in $(gh search prs --label $BRANCH --repo k-capehart/sfdc-dev-org --state open --sort created --json number --json createdAt | jq --arg CREATED "$CREATED" -r '.[] | select(.createdAt < ($CREATED | strftime("%Y-%m-%dT%H:%M:%SZ")))' | jq -r '.number'); do
            gh pr close $pr_number --repo k-capehart/sfdc-dev-org --comment "This Back PR was automatically closed because a more recent PR for this branch was merged." --delete-branch
          done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}