name: Back Propagate

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string

jobs:
  back-propagate:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Create PR"
        run: gh pr create -B ${{ inputs.env_name }} -H main --title '${{ github.event.pull_request.title }}' --body 'Created by GitHub Action'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
