name: Back PR Merged

on:
  pull_request:
    types: [closed]
    branches: [dev]
    paths:
      - "force-app/**"

jobs:
  deploy-scratch-dev:
    if: github.event.pull_request.base.ref == 'dev' && github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[BACK PR]')
    uses: ./.github/workflows/deploy.yml
    secrets:
      sfdx_token: ${{ secrets.SFDX_AUTH_URL }}

  deploy-scratch-staging:
    if: github.event.pull_request.base.ref == 'staging' && github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[BACK PR]')
    uses: ./.github/workflows/deploy.yml
    secrets:
      sfdx_token: ${{ secrets.SFDX_AUTH_URL }}
