name: Deploy to Salesforce

on:
  workflow_call:
    inputs:
      from:
        required: true
        type: string
      to:
        required: true
        type: string
      destructive:
        required: false
        type: string
        default: "false"
    secrets:
      sfdx_token:
        required: true
      slack_webhook_url:
        required: true

jobs:
  deploy-to-salesforce:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install sf cli"
        run: npm install @salesforce/cli --global

      - name: "Install sfdx-git-delta"
        run: echo y | sf plugins install sfdx-git-delta

      - name: "Authenticate using SFDX_AUTH_URL"
        run: echo ${{ secrets.sfdx_token }} | sf org login sfdx-url -s -u

      - name: "Deploy"
        id: deploy
        run: |
          if [ `git diff --name-only ${{ inputs.from }} ${{ inputs.to }} force-app/main/default | wc -l` -ne 0 ]; then
            sf sgd source delta --to "${{ inputs.to }}" --from "${{ inputs.from }}" -o "." -i .forceignore --ignore-destructive-file .forceignoreDestructive
            if [ "${{ inputs.destructive }}" = "true" ]; then
              sf project deploy start -x package/package.xml -w 60 --ignore-conflicts --post-destructive-changes destructiveChanges/destructiveChanges.xml
            else
              if grep -q "<types>" package/package.xml; then
                sf project deploy start -x package/package.xml -w 60 --ignore-conflicts
              else
                echo "No components found in package.xml - nothing to deploy, treating as success"
              fi
            fi
          else
            echo "No changes detected in force-app/main/default"
          fi

      - name: "Slack Notify Success"
        if: success() && github.event.pull_request.base.ref == 'main'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          channel="#github-notifications"
          title=":white_check_mark: Deployment Succeeded"
          body=$(printf "%s" "$PR_TITLE" | sed 's/"/\\"/g')
          pr_url="<https://github.com/${{ github.repository }}/pull/$PR_NUMBER|View in GitHub>"
          log_url="<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
          payload=$(jq -n --arg channel "$channel" --arg title "$title" --arg body "$body" --arg pr_url "$pr_url" --arg log_url "$log_url" '{"channel": $channel, "blocks": [{ "type": "section", "text": { "type": "plain_text", "text": $title }}, { "type": "section", "text": { "type": "plain_text", "text": $body } }, { "type": "section", "text": { "type": "mrkdwn", "text": $pr_url } }, { "type": "section", "text": { "type": "mrkdwn", "text": $log_url } } ]}')
          curl -X POST -H 'Content-type: application/json' --data "$payload" "${{ secrets.slack_webhook_url }}"

      - name: "Slack Notify Failure"
        if: failure()
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          channel="#github-notifications"
          title=":x: Deployment Failed (${{ github.event.pull_request.base.ref }})"
          body=$(printf "%s" "$PR_TITLE" | sed 's/"/\\"/g')
          pr_url="<https://github.com/${{ github.repository }}/pull/$PR_NUMBER|View in GitHub>"
          log_url="<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
          payload=$(jq -n --arg channel "$channel" --arg title "$title" --arg body "$body" --arg pr_url "$pr_url" --arg log_url "$log_url" '{"channel": $channel, "blocks": [{ "type": "section", "text": { "type": "plain_text", "text": $title }}, { "type": "section", "text": { "type": "plain_text", "text": $body } }, { "type": "section", "text": { "type": "mrkdwn", "text": $pr_url }, { "type": "section", "text": { "type": "mrkdwn", "text": $log_url } } ]}')
          curl -X POST -H 'Content-type: application/json' --data "$payload" "${{ secrets.slack_webhook_url }}"

      - name: "Create Release"
        if: success() && github.event.pull_request.base.ref == 'main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VER=$(date +%s)
          LATEST_VER=$(gh release view --json tagName | jq -r .tagName)
          gh release create ${VER} --generate-notes --latest --target main --notes-start-tag ${LATEST_VER}
