name: Back Propagate - Deploy

on:
  workflow_call:
    secrets:
      sfdx_token:
        required: true

jobs:
  back-propagate:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0
      
      - name: "Install sf cli"
        run: npm install @salesforce/cli --global

      - name: "Install sfdx-git-delta"
        run: echo y | sf plugins install sfdx-git-delta

      - name: "Authenticate using SFDX_AUTH_URL"
        run: echo ${{ secrets.sfdx_token }} | sf org login sfdx-url -s -u

      - name: "Deploy"
        id: deploy
        run: |
          sf sgd source delta --to "HEAD" --from "HEAD^" -o "."
          sf project deploy start -x package/package.xml --post-destructive-changes destructiveChanges/destructiveChanges.xml -w 30 --ignore-conflicts
        continue-on-error: true

      - name: "Deploy without destructive changes"
        if: steps.deploy.outcome == 'failure'
        run: sf project deploy start -x package/package.xml -w 30 --ignore-conflicts