name: Deploy to Salesforce

on:
  workflow_call:
    inputs:
      from:
        required: true
        type: string
      to:
        required: true
        type: string
    secrets:
      sfdx_token:
        required: true
      slack_webhook_url:
        required: true

jobs:
  deploy-to-salesforce:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install sf cli"
        run: npm install @salesforce/cli --global

      - name: "Install sfdx-git-delta"
        run: echo y | sf plugins install sfdx-git-delta

      - name: "Authenticate using SFDX_AUTH_URL"
        run: echo ${{ secrets.sfdx_token }} | sf org login sfdx-url -s -u

      - name: "Deploy"
        id: deploy
        run: |
          sf sgd source delta --to "${{ inputs.to }}" --from "${{ inputs.from }}" -o "."
          sf project deploy start -x package/package.xml -w 30 --ignore-conflicts

      - name: "Slack Notify Success"
        if: ${{ success() }}
        run: |
          LOG_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          message=":check: Deployment Succeeded (${{ github.event.pull_request.base.ref }}): ${{ github.event.pull_request.title }}\n<${LOG_URL}|View in GitHub>\n${{ github.event.pull_request.body }}"
          payload=$(jq -n --arg channel "#github-notifications" --arg text "$message" '{channel: $channel, text: $text}')
          curl -X POST -H 'Content-type: application/json' --data "$payload" "${{ secrets.slack_webhook_url }}"

      - name: "Slack Notify Failure"
        if: ${{ failure() }}
        run: |
          LOG_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          message=":x: Deployment Failed (${{ github.event.pull_request.base.ref }}): ${{ github.event.pull_request.title }}\n<${LOG_URL}|View in GitHub>\nThe deployment failed. Please check the logs for more details."
          payload=$(jq -n --arg channel "#github-notifications" --arg text "$message" '{channel: $channel, text: $text}')
          curl -X POST -H 'Content-type: application/json' --data "$payload" "${{ secrets.slack_webhook_url }}"
