name: Back Propagate - Deploy

on:
  workflow_call:
    secrets:
      SFDX_AUTH_URL:
        required: true

jobs:
  back-propagate:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Authenticate using SFDX_AUTH_URL'
        run: echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -u

      - name: "Deploy"
        run: sf project deploy start -l RunLocalTests -w 30 --ignore-conflicts