name: Back Propagate - Deploy

on:
  workflow_call:
    secrets:
      SFDX_AUTH_URL:
        required: true

jobs:
  back-propagate:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0
      
      - name: "Install sfdx-git-delta"
        run: echo y | sf plugins install sfdx-git-delta

      - name: "Authenticate using SFDX_AUTH_URL"
        run: echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -u

      - name: "Deploy"
        run: |
          git fetch --all
          git checkout dev
          git pull origin dev
          sf sgd source delta --to "HEAD" --from "HEAD^" --output "."
          sf project deploy start -x package/package.xml --post-destructive-changes destructiveChanges/destructiveChanges.xml -l RunLocalTests -w 30 --ignore-conflicts