name: Flow Actions

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize]
    paths:
      - "force-app/main/default/flows/**"

jobs:
  flow-lens:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest

      - name: "Run flow lens"
        run: |
          deno run \
            --allow-read \
            --allow-write \
            --allow-env \
            --allow-net \
            --allow-run \
          jsr:@goog/flow-lens \
          --mode="github_action" \
          --diagramTool="mermaid" \
          --gitDiffFromHash="HEAD^1" \
          --gitDiffToHash="HEAD"
