name: Flow Actions

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize]
    paths:
      - "force-app/main/default/flows/**"

jobs:
  flow-lens:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Run flow lens"
        run: |
          deno run \
          --allow-read --allow-write \
          jsr:@goog/flow-lens \
          --mode="github_action" \
          --diagramTool="mermaid" \
          --gitDiffFromHash=${{ github.event.pull_request.base.sha }} \
          --gitDiffToHash=${{ github.event.pull_request.head.sha }} \
          --filePath="force-app/main/default/flows/AccountFlow.flow-meta.xml"
