name: Flow Actions

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize]
    paths:
      - "force-app/main/default/flows/**"

jobs:
  flow-lens:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest

      - name: "Run flow lens"
        run: |
          deno run \
            --allow-read \
            --allow-write \
            --allow-env \
            --allow-net \
            --allow-run \
          jsr:@goog/flow-lens \
          --mode="github_action" \
          --diagramTool="mermaid" \
          --gitDiffFromHash="HEAD^1" \
          --gitDiffToHash="HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sfdx-hardis:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install sf cli"
        run: npm install @salesforce/cli --global

      - name: "Install sfdx-hardis"
        run: echo y | sf plugins install sfdx-hardis

      - name: "Run sfdx-hardis"
        run: |
          sf hardis:project:generate:flow-git-diff \
            --flow "force-app/main/default/flows/AccountFlow.flow-meta.xml" \
            --commit-before "${{ github.event.pull_request.base.sha }}" \
            --commit-after "${{ github.event.pull_request.head.sha }}"
