name: Validate PR on develop branch

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'force-app/**'

jobs:
  validate-deployment-on-develop-org:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:      
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 'Authenticate using SFDX_AUTH_URL'
        shell: bash
        run: | 
<<<<<<< HEAD
          echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -a dev -u -
=======
          echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -a dev -u
>>>>>>> aa3a36378e84c68c38c5f60dc0dc2498490108e7

      - name: 'Validate'
        run: |
          sf project deploy validate -d force-app/ -l RunLocalTests -w 30 -o dev
