name: Validate pull request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - 'force-app/**'

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:      
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Install sfdx-scanner'
        run: |
          sf plugins install @salesforce/sfdx-scanner

      - name: 'Authenticate using SFDX_AUTH_URL'
        run: | 
          echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -a dev -u
      
      - name: 'Scan code'
        run: |
          sf scanner run -e pmd -t . --normalize-severity --severity-threshold 2
      
      - name: 'Run Tests'
        run: |
          sf apex run test --test-level RunLocalTests -w 30 --concise
