name: Validate pull request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - "force-app/**"

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install sf cli"
        run: npm install @salesforce/cli --global

      - name: "Install sfdx-scanner"
        run: sf plugins install @salesforce/sfdx-scanner

      - name: "Install sfdx-git-delta"
        run: echo y | sf plugins install sfdx-git-delta

      - name: "Authenticate using SFDX_AUTH_URL"
        run: echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -a dev -u

      - name: "Scan code"
        run: sf scanner run -e pmd -t . --normalize-severity --severity-threshold 2

      - name: "Validate Build and Run Tests"
        run: |
          sf sgd source delta --to "HEAD" --from "HEAD^" -o "." -i .forceignore
          echo "Validating..."
          OUTPUT=$(sf project deploy validate -x package/package.xml -l RunLocalTests -w 30 2>&1)
          STATUS=$?
          echo "Done"
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "No local changes to deploy"; then
            exit 0
          fi
          exit $STATUS
