name: Manual Deploy Between Branches

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Deploy to:"
        required: true
        type: choice
        options:
          - dev
          - staging
          - main
        default: "dev"

jobs:
  deploy-prod:
    if: github.event.inputs.target_branch == 'main'
    uses: ./.github/workflows/deploy.yml
    secrets:
      sfdx_token: ${{ secrets.SFDX_AUTH_URL }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      from: "HEAD^"
      to: "HEAD"
      destructive: true

  deploy-sandbox:
    if: github.event.inputs.target_branch != 'main'
    uses: ./.github/workflows/deploy.yml
    secrets:
      sfdx_token: ${{ secrets.SFDX_AUTH_URL }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      from: "HEAD^"
      to: "HEAD"
      destructive: true
