name: Manual Deploy Between Branches

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Source branch name"
        required: true
        type: string
        default: "main"
      target_branch:
        description: "Target branch name"
        required: true
        type: string
        default: "dev"

jobs:
  deploy-between-branches:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
          fetch-depth: 0

      - name: "Install sf cli"
        run: npm install @salesforce/cli --global

      - name: "Install sfdx-git-delta"
        run: echo y | sf plugins install sfdx-git-delta

      - name: "Authenticate using SFDX_AUTH_URL"
        run: echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -u

      - name: "Deploy differences between branches"
        id: deploy
        run: |
          echo "Deploying changes from ${{ github.event.inputs.source_branch }} to ${{ github.event.inputs.target_branch }}"
          sf sgd source delta --to "${{ github.event.inputs.target_branch }}" --from "${{ github.event.inputs.source_branch }}" -o "."
          sf project deploy start -x package/package.xml -w 30 --ignore-conflicts
