name: Manual Deploy Between Branches

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Source branch name"
        required: true
        type: string
        default: "main"
      target_branch:
        description: "Target branch name"
        required: true
        type: string
        default: "dev"

jobs:
  deploy-prod:
    if: github.event.inputs.source_branch == 'main'
    uses: ./.github/workflows/deploy.yml
    secrets:
      sfdx_token: ${{ secrets.SFDX_AUTH_URL }}
    with:
      from: "origin/${{ github.event.inputs.source_branch }}"
      to: "origin/${{ github.event.inputs.target_branch }}"

  deploy-sandbox:
    if: github.event.inputs.source_branch != 'main'
    uses: ./.github/workflows/deploy.yml
    secrets:
      sfdx_token: ${{ secrets.SFDX_AUTH_URL }}
    with:
      from: "origin/${{ github.event.inputs.source_branch }}"
      to: "origin/${{ github.event.inputs.target_branch }}"
