name: Validate pull requests when opened or synchronized

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-prod:
    needs: check-if-branch-is-up-to-date
    if: github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/validate.yml
    secrets:
      sfdx_token: ${{ secrets.SFDX_AUTH_URL }}
    with:
      branch_name: ${{ github.event.pull_request.base.ref }}
      from: "HEAD^"
      to: "HEAD"

  validate-sandbox:
    needs: check-if-branch-is-up-to-date
    if: github.event.pull_request.base.ref != 'main'
    uses: ./.github/workflows/validate.yml
    secrets:
      sfdx_token: ${{ secrets.SFDX_AUTH_URL }}
    with:
      branch_name: ${{ github.event.pull_request.base.ref }}
      from: "HEAD^"
      to: "HEAD"z
