name: Validate pull requests when opened or synchronized

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "force-app/**"

jobs:
  check-if-validation-needed:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if branch is ahead of base branch
        run: |
          if ! git merge-base --is-ancestor origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }}; then
            echo "This branch is not up to date with ${{ github.event.pull_request.base.ref }}"
            exit 1
          fi

      - name: "Check for changes"
        run: |
          if [ `git status force-app/main/default --porcelain=1 | wc -l` -eq 0 ]; then
            echo "No changes detected in force-app/main/default"
            exit 0
          fi

  validate-prod:
    runs-on: ubuntu-latest
    needs: check-if-validation-needed
    if: ${{ github.event.pull_request.base.ref }} == 'main'
    steps:
      - name: "Call validation workflow"
        uses: ./.github/workflows/validate.yml
        with:
          sfdx_token: ${{ secrets.SFDX_AUTH_URL }}
          branch_name: ${{ github.event.pull_request.base.ref }}

  validate-sandbox:
    runs-on: ubuntu-latest
    needs: check-if-validation-needed
    if: ${{ github.event.pull_request.base.ref }} != 'main'
    steps:
      - name: "Call validation workflow"
        uses: ./.github/workflows/validate.yml
        with:
          sfdx_token: ${{ secrets.SFDX_AUTH_URL }}
          branch_name: ${{ github.event.pull_request.base.ref }}
