name: Pushed to Main

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy-to-prod:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy.yml
    secrets:
      sfdx_token: ${{ secrets.SFDX_AUTH_URL }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      from: ${{ github.event.pull_request.base.ref }}
      to: ${{ github.event.pull_request.head.ref }}

  create-pr-dev:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/back-pr.yml
    with:
      branch_name: dev
    secrets: inherit
