name: Pushed to Main

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  create-pr-dev:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/back-pr.yml
    with:
      branch_name: dev
    secrets: inherit
