name: Deploy project for Release

on:
    release:
      types: [published]

jobs:
    deploy-release:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
                  
            - name: 'Install Salesforce CLI'
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
                  mkdir sf
                  tar xJf sf-linux-x64.tar.xz -C sf --strip-components 1
                  echo "sf/bin/" >> $GITHUB_PATH
                  sf/bin/sf version
                  
            - name: 'Populate auth file with SFDX_URL secret of integration org'
              shell: bash
              run: |
                  echo ${{ secrets.SFDX_INTEGRATION_URL}} > ./SFDX_INTEGRATION_URL.txt

            - name: 'Authenticate to Integration Org'
              run: sf/bin/sf auth sfdxurl store -f ./SFDX_INTEGRATION_URL.txt -s -a integration

            - name: 'Validate'
              run: |
                  sf/bin/sf project deploy start -d force-app/ -c -l RunLocalTests -w 30
