name: Deploy project for Release

on:
  release:
    types: [published]

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
            
      - name: 'Authenticate using SF_ACCESS_TOKEN'
        shell: bash
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
          sf org login sfdx-url -s -a dev -f sfdx_auth

      - name: 'Validate'
        run: |
          sf project deploy start -d force-app/ -c -l RunLocalTests -w 30 -o dev
