name: Validate pull request

on:
  workflow_call:
    secrets:
      sfdx_token:
        required: true
    inputs:
      branch_name:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Check for changes"
        run: |
          if [ `git status force-app/main/default --porcelain=1 | wc -l` -eq 0 ]; then
            echo "No changes detected in force-app/main/default"
            exit 0
          fi

      - name: "Install sf cli"
        run: npm install @salesforce/cli --global

      - name: "Install sfdx-git-delta"
        run: echo y | sf plugins install sfdx-git-delta

      - name: "Authenticate using SFDX_AUTH_URL"
        run: echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -a dev -u

        # the validate command is recommended only for production, as it enforces tests
      - name: "Run validation"
        run: |
          sf sgd source delta --to "HEAD" --from "HEAD^" -o "." -i .forceignore
          if [ ${{ inputs.branch_name }} == 'main' ]; then
            sf project deploy validate -x package/package.xml -l RunLocalTests -w 45
          else
            sf project deploy start -x package/package.xml --dry-run -w 45
          fi
